// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kezauwmcyrigowmgqewu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlemF1d21jeXJpZ293bWdxZXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjk0NTEsImV4cCI6MjA2NTkwNTQ1MX0.WhUjhQuSPcn_q-EeXDyPPzMMMX5OfZ6tw3au5wttNe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);